name: Build AutoBSPpackingTool

on:
  push:
    branches: [ main, dev]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Framework 4.0 Targeting Pack
      run: |
        # Download and install .NET Framework 4.0 Developer Pack directly
        $url = "https://download.microsoft.com/download/A/6/7/A678AB47-496B-4907-B3C7-6DFB75AE19C6/dotNetFx40_Full_x86_x64.exe"
        $output = "$env:TEMP\dotNetFx40_Full_x86_x64.exe"
        Write-Host "Downloading .NET Framework 4.0..."
        Invoke-WebRequest -Uri $url -OutFile $output
        Write-Host "Installing .NET Framework 4.0..."
        Start-Process -FilePath $output -ArgumentList "/quiet" -Wait
        
        # Also install targeting pack via VS Build Tools
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --includeRecommended" -y
        choco install netfx-4.0-devpack -y
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.fsproj', '**/*.vbproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: |
        # Try dotnet restore first, fallback to nuget restore
        try {
          dotnet restore
        } catch {
          Write-Host "dotnet restore failed, trying nuget restore..."
          nuget restore
        }
      shell: pwsh

    - name: Build solution
      run: |
        # Try dotnet build first, fallback to msbuild
        try {
          dotnet build --configuration ${{ matrix.configuration }} --no-restore --verbosity minimal
        } catch {
          Write-Host "dotnet build failed, trying msbuild..."
          msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform="Any CPU" /verbosity:minimal
        }
      shell: pwsh

    - name: Run tests (if any)
      run: |
        if (Test-Path "**/*Tests*.csproj") {
          dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity minimal --logger trx --collect:"XPlat Code Coverage"
        } else {
          Write-Host "No test projects found - skipping tests"
        }
      shell: pwsh
      continue-on-error: true

    - name: Publish application
      if: matrix.configuration == 'Release'
      run: |
        dotnet publish --configuration Release --no-build --output ./publish --self-contained true --runtime win-x64
        
    - name: Create portable package
      if: matrix.configuration == 'Release'
      run: |
        Compress-Archive -Path "./publish/*" -DestinationPath "./AutoBSPpackingTool-${{ github.ref_name }}-win-x64.zip"
      shell: pwsh

    - name: Upload build artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: AutoBSPpackingTool-${{ github.ref_name }}-win-x64
        path: ./publish/
        retention-days: 30

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework Developer Pack
      run: |
        # Install .NET Framework 4.0 Developer Pack
        choco install netfx-4.0-devpack -y
        # Install additional framework versions for compatibility
        choco install netfx-4.5.2-devpack netfx-4.6.1-devpack netfx-4.7.2-devpack netfx-4.8-devpack -y
      shell: pwsh

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build and publish release
      run: |
        dotnet publish --configuration Release --output ./release --self-contained true --runtime win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Create release package
      run: |
        Compress-Archive -Path "./release/*" -DestinationPath "./AutoBSPpackingTool-${{ github.ref_name }}-win-x64.zip"
      shell: pwsh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./AutoBSPpackingTool-${{ github.ref_name }}-win-x64.zip
        draft: false
        prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-analysis:
    runs-on: windows-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Run code analysis
      run: |
        dotnet build --configuration Release --verbosity minimal --warnaserror
        
    - name: Security scan
      uses: securecodewarrior/github-action-add-sarif@v1
      if: always()
      continue-on-error: true
      with:
        sarif-file: 'results.sarif'
